version: 2
mergeable:
  - when: pull_request.*
    name: "Description check"

    filter: # to ignore Feedback branch
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none

    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.

  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'

    filter: # to ignore Feedback branch
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none

    branches-ignore:
      - main
    validate:
      - do: approvals
        min:
          count: 2
        required:
          requested_reviewers: true
          message: All requested reviewers must approve changes before merging.
        limit:
          users: [ 'qrutyy', 'spisladqo', 'kar1mgh' ]