#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

echo "Running git pre-commit hook"

./gradlew ktfmtCheck

checkStatus=$?

if [ $checkStatus -ne 0 ]
then
  echo "To apply formatter run ${bold}./gradlew ktfmtFormat${normal}"
  echo "Don't forget to ${bold}git add${normal} all formatted files"
  exit 1
else
  exit 0
fi


