name: ktfmt

on:
  workflow_dispatch:
  pull_request:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "ktfmt"
        uses: rsookram/ktfmt-action@v1
        with:
          style: dropbox