name: ktfmt

on:
  pull_request:


jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: "ktfmt"
        uses: rsookram/ktfmt-action@v1
        with:
          style: dropbox