name: Build & Run JUnit5 tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    if: github.actor!= 'github-classroom[bot]' # to ignore Feedback branch

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu

      - name: Build & Test by Gradle
        run: ./gradlew build